const { Card } = require('./entities');

const fullDeck = [
  new Card('AC', 1),
  new Card('2C', 2),
  new Card('3C', 3),
  new Card('4C', 4),
  new Card('5C', 5),
  new Card('6C', 6),
  new Card('7C', 7),
  new Card('8C', 8),
  new Card('9C', 9),
  new Card('10C', 10),
  new Card('JC', 11),
  new Card('QC', 12),
  new Card('KC', 13),
  new Card('AH', 1),
  new Card('2H', 2),
  new Card('3H', 3),
  new Card('4H', 4),
  new Card('5H', 5),
  new Card('6H', 6),
  new Card('7H', 7),
  new Card('8H', 8),
  new Card('9H', 9),
  new Card('10H', 10),
  new Card('JH', 11),
  new Card('QH', 12),
  new Card('KH', 13),
  new Card('AS', 1),
  new Card('2S', 2),
  new Card('3S', 3),
  new Card('4S', 4),
  new Card('5S', 5),
  new Card('6S', 6),
  new Card('7S', 7),
  new Card('8S', 8),
  new Card('9S', 9),
  new Card('10S', 10),
  new Card('JS', 11),
  new Card('QS', 12),
  new Card('KS', 13),
  new Card('AD', 1),
  new Card('2D', 2),
  new Card('3D', 3),
  new Card('4D', 4),
  new Card('5D', 5),
  new Card('6D', 6),
  new Card('7D', 7),
  new Card('8D', 8),
  new Card('9D', 9),
  new Card('10D', 10),
  new Card('JD', 11),
  new Card('QD', 12),
  new Card('KD', 13),
];

module.exports = { fullDeck };
